# Generated by Django 6.0 on 2025-12-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='E-mail do usuário.', max_length=254, unique=True)),
                ('nome', models.CharField(help_text='Nome completo do usuário.', max_length=150)),
                ('cpf', models.CharField(help_text='CPF do usuário.', max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato do usuário.', max_length=15)),
                ('nick_discord', models.CharField(blank=True, help_text='Nick do Discord do usuário.', max_length=50)),
                ('cep', models.CharField(help_text='CEP do endereço do usuário.', max_length=9)),
                ('numero', models.CharField(help_text='Número do endereço do usuário.', max_length=10)),
                ('complemento', models.CharField(blank=True, help_text='Complemento do endereço do usuário.', max_length=50)),
                ('bairro', models.CharField(help_text='Bairro do endereço do usuário.', max_length=50)),
                ('cidade', models.CharField(help_text='Cidade do endereço do usuário.', max_length=50)),
                ('estado', models.CharField(help_text='Estado do endereço do usuário .', max_length=2)),
                ('tipo_usuario', models.CharField(choices=[('DIRETORIA', 'Diretoria'), ('ASSOCIADO', 'Associado'), ('AFILIADO', 'Afiliado'), ('COLETIVO', 'Coletivo'), ('PUBLICO', 'Público')], default='PUBLICO', help_text='Tipo do usuário na plataforma.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
